-- Enhanced Database Schema with Monetization Features
-- Run this in Supabase SQL Editor

-- ============================================
-- 1. PREMIUM MEMBERSHIP SYSTEM
-- ============================================

-- Add subscription fields to profiles
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS subscription_tier text default 'free',
ADD COLUMN IF NOT EXISTS subscription_status text default 'inactive',
ADD COLUMN IF NOT EXISTS subscription_start_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS subscription_end_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS stripe_customer_id text,
ADD COLUMN IF NOT EXISTS stripe_subscription_id text;

-- Create subscription plans table
CREATE TABLE IF NOT EXISTS public.subscription_plans (
  id bigint generated by default as identity primary key,
  name text not null,
  tier text not null unique, -- free, basic, premium, business
  price_monthly decimal(10, 2) not null,
  price_yearly decimal(10, 2),
  features jsonb,
  max_classifieds integer,
  max_directory_listings integer,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default subscription plans
INSERT INTO public.subscription_plans (name, tier, price_monthly, price_yearly, features, max_classifieds, max_directory_listings) VALUES
('Free', 'free', 0, 0, '["View content", "1 classified per month", "Basic support"]', 1, 0),
('Basic', 'basic', 2.00, 20.00, '["Unlimited classifieds", "Priority support", "Ad-free experience"]', -1, 1),
('Premium', 'premium', 5.00, 50.00, '["All Basic features", "Featured classifieds", "3 directory listings", "Analytics"]', -1, 3),
('Business', 'business', 10.00, 100.00, '["All Premium features", "Unlimited directory listings", "Banner ads", "Priority placement"]', -1, -1)
ON CONFLICT (tier) DO NOTHING;

-- ============================================
-- 2. PAYMENT SYSTEM
-- ============================================

-- Create payments table
CREATE TABLE IF NOT EXISTS public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  amount decimal(10, 2) not null,
  currency text default 'KWD',
  payment_type text not null, -- subscription, classified, directory, banner_ad
  payment_method text, -- stripe, paypal
  stripe_payment_id text,
  paypal_payment_id text,
  status text default 'pending', -- pending, completed, failed, refunded
  metadata jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS payments_user_id_idx ON public.payments(user_id);
CREATE INDEX IF NOT EXISTS payments_status_idx ON public.payments(status);

-- ============================================
-- 3. ENHANCED CLASSIFIEDS WITH PAYMENT
-- ============================================

-- Add payment fields to classifieds
ALTER TABLE public.classifieds 
ADD COLUMN IF NOT EXISTS is_featured boolean default false,
ADD COLUMN IF NOT EXISTS is_premium boolean default false,
ADD COLUMN IF NOT EXISTS payment_id bigint references public.payments(id),
ADD COLUMN IF NOT EXISTS boost_until timestamp with time zone;

-- ============================================
-- 4. BUSINESS DIRECTORY
-- ============================================

CREATE TABLE IF NOT EXISTS public.business_directory (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  business_name text not null,
  category text not null,
  subcategory text,
  description text,
  logo_url text,
  cover_image_url text,
  phone text,
  email text,
  website text,
  address text,
  location text,
  working_hours jsonb,
  social_media jsonb,
  listing_type text default 'basic', -- basic, enhanced, featured
  is_verified boolean default false,
  payment_id bigint references public.payments(id),
  views integer default 0,
  rating decimal(3, 2) default 0,
  review_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone
);

CREATE INDEX IF NOT EXISTS business_directory_category_idx ON public.business_directory(category);
CREATE INDEX IF NOT EXISTS business_directory_listing_type_idx ON public.business_directory(listing_type);
CREATE INDEX IF NOT EXISTS business_directory_user_id_idx ON public.business_directory(user_id);

-- Business reviews
CREATE TABLE IF NOT EXISTS public.business_reviews (
  id bigint generated by default as identity primary key,
  business_id bigint references public.business_directory(id) on delete cascade,
  user_id uuid references public.profiles(id),
  rating integer not null check (rating >= 1 and rating <= 5),
  review_text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ============================================
-- 5. BANNER ADVERTISING
-- ============================================

CREATE TABLE IF NOT EXISTS public.banner_ads (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  title text not null,
  image_url text not null,
  link_url text,
  placement text not null, -- header, sidebar, footer, article
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  payment_id bigint references public.payments(id),
  clicks integer default 0,
  impressions integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS banner_ads_placement_idx ON public.banner_ads(placement);
CREATE INDEX IF NOT EXISTS banner_ads_active_idx ON public.banner_ads(is_active);

-- ============================================
-- 6. ENABLE RLS
-- ============================================

ALTER TABLE public.subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_directory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banner_ads ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 7. RLS POLICIES
-- ============================================

-- Subscription plans (public read)
CREATE POLICY "Subscription plans are viewable by everyone"
  ON subscription_plans FOR SELECT
  USING ( is_active = true );

-- Payments (users can view their own)
CREATE POLICY "Users can view own payments"
  ON payments FOR SELECT
  USING ( auth.uid() = user_id );

CREATE POLICY "Users can create payments"
  ON payments FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

-- Business directory (public read, owner write)
CREATE POLICY "Business listings are viewable by everyone"
  ON business_directory FOR SELECT
  USING ( true );

CREATE POLICY "Users can create business listings"
  ON business_directory FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

CREATE POLICY "Users can update own business listings"
  ON business_directory FOR UPDATE
  USING ( auth.uid() = user_id );

-- Business reviews (public read, authenticated write)
CREATE POLICY "Reviews are viewable by everyone"
  ON business_reviews FOR SELECT
  USING ( true );

CREATE POLICY "Authenticated users can create reviews"
  ON business_reviews FOR INSERT
  WITH CHECK ( auth.role() = 'authenticated' );

-- Banner ads (public read for active ads)
CREATE POLICY "Active banner ads are viewable by everyone"
  ON banner_ads FOR SELECT
  USING ( is_active = true AND now() BETWEEN start_date AND end_date );

CREATE POLICY "Users can create banner ads"
  ON banner_ads FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

CREATE POLICY "Users can update own banner ads"
  ON banner_ads FOR UPDATE
  USING ( auth.uid() = user_id );
