-- Enhanced Database Schema for Kuwait Malayali Portal
-- Run this in Supabase SQL Editor

-- Create profiles table to store extra user data
create table public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  avatar_url text,
  role text default 'user',
  bio text,
  phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Create policies
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a trigger to automatically create a profile entry when a new user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'user');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create table for News
create table public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique,
  content text not null,
  content_type text default 'text', -- text, video, youtube
  video_url text, -- For uploaded videos or YouTube URLs
  youtube_id text, -- YouTube video ID
  summary text,
  category text default 'General',
  tags text[],
  image_url text,
  author_id uuid references public.profiles(id),
  views integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_published boolean default false,
  published_at timestamp with time zone
);

-- Create index for better performance
create index news_slug_idx on public.news(slug);
create index news_category_idx on public.news(category);
create index news_published_idx on public.news(is_published, published_at);

-- Create table for Classifieds
create table public.classifieds (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  price decimal(10, 2),
  category text,
  subcategory text,
  image_urls text[],
  user_id uuid references public.profiles(id),
  location text,
  contact_phone text,
  contact_email text,
  views integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone,
  status text default 'pending'
);

-- Create index for classifieds
create index classifieds_category_idx on public.classifieds(category);
create index classifieds_status_idx on public.classifieds(status);

-- Create table for Events
create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  event_date timestamp with time zone not null,
  end_date timestamp with time zone,
  location text,
  venue text,
  image_url text,
  organizer_id uuid references public.profiles(id),
  organizer_name text,
  contact_email text,
  contact_phone text,
  registration_url text,
  max_attendees integer,
  current_attendees integer default 0,
  is_free boolean default true,
  ticket_price decimal(10, 2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index for events
create index events_date_idx on public.events(event_date);

-- Enable RLS on all tables
alter table public.news enable row level security;
alter table public.classifieds enable row level security;
alter table public.events enable row level security;

-- News policies
create policy "News are viewable by everyone"
  on news for select
  using ( is_published = true or auth.uid() = author_id );

create policy "Authenticated users can create news"
  on news for insert
  with check ( auth.uid() = author_id );

create policy "Users can update their own news"
  on news for update
  using ( auth.uid() = author_id );

-- Classifieds policies
create policy "Active classifieds are viewable by everyone"
  on classifieds for select
  using ( status = 'active' or auth.uid() = user_id );

create policy "Authenticated users can create classifieds"
  on classifieds for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own classifieds"
  on classifieds for update
  using ( auth.uid() = user_id );

-- Events policies
create policy "Events are viewable by everyone"
  on events for select
  using ( true );

create policy "Authenticated users can create events"
  on events for insert
  with check ( auth.uid() = organizer_id );

create policy "Users can update their own events"
  on events for update
  using ( auth.uid() = organizer_id );
